### ISSUE TITLE
Don't use Pandas to read CSV

### ISSUE THREAD

**Issue by Prashant-Dwivedi-08-01** [rbl-project/backend#7]
Instead of reading CSV with Pandas and then converting it into SQL db, use SQLALCHEMY to directly convert it into a table in db

**Comment by Prashant-Dwivedi-08-01** [comment]
https://stackoverflow.com/questions/31394998/using-sqlalchemy-to-load-csv-file-into-a-database#:~:text=To%20import%20a%20relatively%20small,section%20of%20the%20sqlalchemy%20tutorial.

**Comment by Dravin101** [comment]
Hello, is it possible to import csv with / or \ inside the string without problems?
